print('Equality and unequality if strings:')
print(f'Equality: bird equal Bird? {"bird"=="Bird"}')
print(f'Unequality: bird unequal Bird? {"bird"!="Bird"}')
print(f'Equality with .lower() method: bird equal Bird in lowercase? {"bird".lower()=="Bird".lower()}')
print('\nNumerial tests:')
print(f'Is 1 equal 1? {1 == 1}')
print(f'Is 1 unequal 1? {1 != 1}')
print(f'Is 1 > 2? {1 > 2}')
print(f'Is 3 < 5? {3 < 5}')
print (f'Is (2+3) >= 5? {(2+3) >= 5}')
print (f'Is 2*3 <= 10/2? {2*3 <= 10/2}')
print('\nKeywords AND and OR:')
print(f'Is 5 > 3 AND 5 < 6? {5 > 3 and 5 < 6}')
print(f'Is 18 > 20 OR 18 < 25? {18 > 20 or 18 < 25}')
print('\nItem in list test:')
fruits = ['apple', 'banana', 'pear', 'lemon']
print(f'Is Apple IN Fruits list? {"apple" in fruits } ')
print(f'Is Pizza IN Fruits list? {"pizza" in fruits } ')
print(f'Is Apple NOT IN Fruits list? {"apple" not in fruits } ')
print(f'Is Pizza NOT IN Fruits list? {"pizza" not in fruits } ')

